services:
  app:
    build: .
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${PORT:-8000}/health"]
      interval: 10s
      timeout: 5s
      retries: 6
  elasticsearch:
    image: elasticsearch:9.1.5
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.license.self_generated.type=${LICENSE:-basic}
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsS http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s >/dev/null || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 30

volumes:
  esdata:
    driver: local
